# Generated by Django 5.2.5 on 2025-08-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_contactmessage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactMessage",
            new_name="Contact_message",
        ),
    ]
