# Generated by Django 5.2.5 on 2025-08-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0003_rename_contactmessage_contact_message"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact_message",
            new_name="ContactMessage",
        ),
    ]
