# Generated by Django 5.2.5 on 2025-08-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0004_rename_contact_message_contactmessage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactMessage",
            new_name="Contact_message",
        ),
    ]
